#!/bin/bash

# urls
x86=http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.2.tar.bz2
x64=http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.2%20x64.tar.bz2
sUrl=$x64

# flag handling
default=true
latex=true
x86f=false

while getopts ":dlx" opt; do
	case $opt in
		d)	default=false	;;
		l)	latex=false	;;
		x)
			sUrl=$x86
			x86f=true	;;
		\?)	;;
	esac
done

echo " <{ Installation of Sublime Text 2 }> \n"

dir=$(dirname -- $(readlink -fn -- "$0"))

echo ">>> begin download of Sublime Text 2\n"
if ! wget --spider $sUrl 2>&1 | grep --quiet "200 OK"
then
	echo "ERROR: Unable to download Sublime Text 2."
	echo "Exiting."
	exit 1
fi
wget $sUrl
echo "<<< end download\n"

echo ">>> begin extrect archive and move files\n"
if [[ $x86f = false ]]
then
	tar -jxvf Sublime\ Text\ 2.0.2\ x64.tar.bz2
	rm Sublime\ Text\ 2.0.2\ x64.tar.bz2
else
	tar -jxvf Sublime\ Text\ 2.0.2.tar.bz2
	rm Sublime\ Text\ 2.0.2.tar.bz2
fi

mv Sublime\ Text\ 2 sublime
sudo rm -f -R /opt/sublime
sudo mv sublime /opt
cd /opt
sudo chown -R root:root sublime
sudo chmod -R +r sublime
echo "<<< end extract and move\n"

echo ">>> begin installing Source Code Pro"

wget http://downloads.sourceforge.net/project/sourcecodepro.adobe/SourceCodePro_FontsOnly-1.017.zip
unzip SourceCodePro_FontsOnly-1.017.zip
mkdir -p ~/.fonts
cp SourceCodePro_FontsOnly-1.017/OTF/*.otf ~/.fonts
fc-cache -f -v
rm -rf SourceCodePro_FontsOnly-1.017

echo ">>> end installing Source Code Pro"

echo ">>> begin configuration\n"
cd $dir

echo " > create terminal access"
sudo cp sublime_text /usr/bin/sublime_text
sudo chmod 775 /usr/bin/sublime_text

echo " > create shortcut"
sudo cp sublime.desktop /usr/share/applications/sublime.desktop

if [ $default = true ]
then
	echo " > set Sublime Text as default editor"
	[ ! -d ~/.local/share ] && mkdir ~/.local/share
	[ ! -d ~/.local/share/applications ] && mkdir ~/.local/share/applications
	mimes[0]='application/x-perl'
	mimes[1]='text/plain'
	mimes[2]='text/x-chdr'
	mimes[3]='text/x-csrc'
	mimes[4]='text/x-dtd'
	mimes[5]='text/x-java'
	mimes[6]='text/mathml'
	mimes[7]='text/x-python'
	mimes[8]='text/x-sql'
	mimes[9]='text/xml'
	defFile=~/.local/share/applications/mimeapps.list
	if [ ! -f $defFile ]
	then
		touch $defFile
		echo "[Default Applications]" >> $defFile
		for item in ${mimes[*]}
		do
			echo "$item=sublime.desktop" >> $defFile
		done
	else
		for item in ${mimes[*]}
		do
			pattern="$(echo $item | sed -e 's/[^-A-Za-z0-9_]/\\&/g')"
			if grep -Pq '^('$pattern')=([^;]+)(\.desktop)$' $defFile
			then
				sed -r 's/^('$pattern')=([^;]+)(\.desktop)$/\1=sublime\3/g' -i $defFile
			else
				sed -r 's/(\[Added Associations\])/'${pattern}'=sublime.desktop\n\n\1/' -i $defFile
			fi
		done
	fi
fi

echo " > installing package control"
if ! wget --spider https://sublime.wbond.net/Package%20Control.sublime-package 2>&1 | grep --quiet "200 OK"
then
	echo "ERROR: Could not download Package Control."
	echo " You have to install it and all packeges manually. See Readme."
else
	if [ ! -d ~/.config/sublime-text2 ]
	then
		mkdir ~/.config/sublime-text-2
		mkdir ~/.config/sublime-text-2/Packages
		mkdir ~/.config/sublime-text-2/Installed\ Packages
	fi
	wget -q https://sublime.wbond.net/Package%20Control.sublime-package
	mv Package\ Control.sublime-package ~/.config/sublime-text-2/Installed\ Packages/Package\ Control.sublime-package

	echo " > installing packages"

	# Theme and user seetings
	cp -R Packages/ ~/.config/sublime-text-2/
	echo "   - moved theme and defaults"

	# SFTP
	echo "   - NOTE: Don't forget SFTP, via Package Control!"

	# ColorHighlighter
	git clone https://github.com/Monnoroch/ColorHighlighter.git
	rm -Rf ColorHighlighter/.git
	mv ColorHighlighter ~/.config/sublime-text-2/Packages/
	echo "   - moved ColorHighlighter"

	# ColorPicker
	git clone https://github.com/weslly/ColorPicker.git
	rm -Rf ColorPicker/.git
	mv ColorPicker ~/.config/sublime-text-2/Packages/
	echo "   - moved ColorPicker"

	# ColorSchemeEditor
	git clone https://github.com/bobef/ColorSchemeEditor.git
	rm -Rf ColorSchemeEditor/.git
	mv ColorSchemeEditor ~/.config/sublime-text-2/Packages/
	echo "   - moved ColorSchemeEditor"

	# D3.js Snippets
	git clone https://github.com/fabriciotav/d3-snippets-for-sublime-text-2.git
	rm -Rf d3-snippets-for-sublime-text-2/.git
	mkdir ~/.config/sublime-text-2/Packages/D3.js\ Snippets
	mv d3-snippets-for-sublime-text-2/ ~/.config/sublime-text-2/Packages/
	echo "   - moved D3.js Snippets"

	# Emmet
	git clone https://github.com/sergeche/emmet-sublime.git
	rm -Rf emmet-sublime/.git
	mkdir ~/.config/sublime-text-2/Packages/Emmet
	mv emmet-sublime/* ~/.config/sublime-text-2/Packages/Emmet/
	echo "   - moved Emmet"

	# GitGutter
	git clone https://github.com/jisaacks/GitGutter.git
	rm -Rf GitGutter/.git
	mv GitGutter ~/.config/sublime-text-2/Packages/
	echo "   - moved GitGutter"

	# jQuery (some snippets)
	git clone https://github.com/SublimeText/jQuery.git
	rm -Rf jQuery/.git
	mv jQuery ~/.config/sublime-text-2/Packages/
	echo "   - moved jQuery"

	# LaTeXTools
	if [ $latex = true ]
	then
		sudo apt-get install texlive texlive-latex-extra latexmk pgf
		git clone https://github.com/SublimeText/LaTeXTools.git
		rm -Rf LaTeXTools/.git
		mv LaTeXTools ~/.config/sublime-text-2/Packages/
		echo "   - moved LaTeXTools"
	fi

	# More Layouts
	git clone https://github.com/unknownuser88/morelayouts.git
	rm -Rf morelayouts/.git
	mkdir ~/.config/sublime-text-2/Packages/More\ Layouts
	mv morelayouts/* ~/.config/sublime-text-2/Packages/More\ Layouts/
	echo "   - moved More Layouts"

	# PHPDoc
	git clone https://github.com/SublimeText/PhpDoc.git
	rm -Rf PhpDoc/.git
	mv PhpDoc ~/.config/sublime-text-2/Packages/
	echo "   - moved PHPDoc"

	# QuoteHTML
	git clone https://github.com/mutian/Sublime-Quote-HTML.git
	rm -Rf Sublime-Quote-HTML/.git
	mkdir ~/.config/sublime-text-2/Packages/QuoteHTML
	mv Sublime-Quote-HTML/* ~/.config/sublime-text-2/Packages/QuoteHTML/
	echo "   - moved QuoteHTML"

	# SASS
	git clone https://github.com/nathos/sass-textmate-bundle.git
	rm -Rf sass-textmate-bundle/.git
	mkdir ~/.config/sublime-text-2/Packages/Sass
	mv sass-textmate-bundle/* ~/.config/sublime-text-2/Packages/Sass/
	echo "   - moved SASS"

	# SFTP Custom Commands
	git clone https://github.com/FBeuster/SFTP-Custom-Commands.git
	rm -Rf SFTP-Custom-Commands/.git
	mkdir ~/.config/sublime-text-2/Packages/SFTP\ Custom\ Commands
	mv SFTP-Custom-Commands/* ~/.config/sublime-text-2/Packages/SFTP\ Custom\ Commands/
	echo "   - moved SFTP Custom Commands"

	# Theme - Brogrammer
	git clone https://github.com/FBeuster/brogrammer-theme.git
	rm -Rf brogrammer-theme/.git
	mkdir ~/.config/sublime-text-2/Packages/Theme\ -\ Brogrammer
	mv brogrammer-theme/* ~/.config/sublime-text-2/Packages/Theme\ -\ Brogrammer/
	echo "   - moved Theme - Brogrammer"

	touch ~/.config/sublime-text-2/Packages/Theme\ -\ Default/Widget.sublime-settings
	cat >~/.config/sublime-text-2/Packages/Theme\ -\ Default/Widget.sublime-settings <<EOF
{
	"color_scheme": "Packages/Theme - Brogrammer/Widgets.stTheme"
}
EOF
	echo "   - configured Theme - Brogrammer"


fi

echo "<<< end configuration\n"
