#!/bin/bash

# flag handling
default=true

for i in $*
do
	case $i in
		"-d") default=false
		;;
	esac
done

echo " <{ Installation of Sublime Text 2 }> \n"

dir=$(dirname -- $(readlink -fn -- "$0"))

echo ">>> begin download of Sublime Text 2\n"
wget http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.2%20x64.tar.bz2
echo "<<< end download\n"

echo ">>> begin extrect archive and move files\n"
tar -jxvf Sublime\ Text\ 2.0.2\ x64.tar.bz2
rm Sublime\ Text\ 2.0.2\ x64.tar.bz2

mv Sublime\ Text\ 2 sublime
sudo rm -f -R /opt/sublime
sudo mv sublime /opt
cd /opt
sudo chown -R root:root sublime
sudo chmod -R +r sublime
echo "<<< end extract and move\n"

echo ">>> begin configuration\n"

echo " > create terminal access"
cd $dir
sudo cp sublime_text /usr/bin/sublime_text
sudo chmod 775 /usr/bin/sublime_text

echo " > create shortcut"
sudo cp sublime.desktop /usr/share/applications/sublime.desktop

if [ $default = true ]
then
	echo " > set Sublime Text as default editor"
	cd ~/.local/share/applications/
	mimes[0]='application/x-perl'
	mimes[1]='text/plain'
	mimes[2]='text/x-chdr'
	mimes[3]='text/x-csrc'
	mimes[4]='text/x-dtd'
	mimes[5]='text/x-java'
	mimes[6]='text/mathml'
	mimes[7]='text/x-python'
	mimes[8]='text/x-sql'
	mimes[9]='text/xml'
	defFile="mimeapps.list"
	for item in ${mimes[*]}
	do
		pattern="$(echo $item | sed -e 's/[^-A-Za-z0-9_]/\\&/g')"
		if grep -Pq '^('$pattern')=([^;]+)(\.desktop)$' $defFile
		then
			sed -r 's/^('$pattern')=([^;]+)(\.desktop)$/\1=sublime\3/g' -i $defFile
		else
			sed '/^$/d' -i a.txt
			sed -r 's/(\[Added Associations\])/'${pattern}'=sublime.desktop\n\n\1/' -i $defFile
		fi
	done
fi

echo "<<< end configuration\n"
